Repository wisemen-digital/nestjs-project-template, pull requests merged in 2024-09, with the labels that each got.

#100 [Bugfix] Fix issue that resulted in deadlocks when running tests locally
  src/modules/localization/generated/i18n.generated.ts
  src/modules/roles/tests/seeders/role.seeder.ts
  src/modules/typesense/tests/import-typesense.job.test.ts
  src/modules/users/use-cases/view-users/view-users.e2e.test.ts
  src/utils/test-setup/global-setup.ts
  src/utils/test-setup/setup.ts
Labels: 📃 XS PR, 🛠️ bugfix

#106 created validation & exception modules
  src/app.module.ts
  src/entrypoints/api.ts
  src/modules/auth/middleware/auth.middleware.ts
  src/modules/auth/modules/auth.module.ts
  src/modules/exceptions/api-errors/api-error-code.decorator.ts
  src/modules/exceptions/api-errors/api-error-meta.decorator.ts
  src/modules/exceptions/api-errors/api-error-response.ts
  src/modules/exceptions/api-errors/api-error-status.decorator.ts
  src/modules/exceptions/api-errors/api-error.ts
  src/modules/exceptions/api-errors/bad-request.api-error.ts
  src/modules/exceptions/api-errors/conflict.api-error.ts
  src/modules/exceptions/api-errors/not-found.api-error.ts
  src/modules/exceptions/exception.filter.ts
  src/modules/exceptions/exception.module.ts
  src/modules/exceptions/generic/not-found.error.ts
  src/modules/exceptions/generic/unauthorized.error.ts
  src/modules/exceptions/types/json-api-error.type.ts
  src/modules/permissions/transformers/permission.transformer.ts
  src/modules/roles/services/role.service.ts
  src/modules/roles/types/role-name-already-in-use.error.ts
  src/modules/roles/types/role-not-editable.error.ts
  src/modules/users/use-cases/change-password/change-password.controller.ts
  src/modules/users/use-cases/change-password/invalid-old-password.error.ts
  src/modules/users/use-cases/register-user/email-already-in-use.error.ts
  src/modules/users/use-cases/register-user/register-user.controller.ts
  src/modules/validation/convert-validation-errors.ts
  src/modules/validation/validation.module.ts
  src/modules/validation/validation.pipe.ts
  src/utils/exceptions/errors.interceptor.ts
  src/utils/exceptions/generic/not-found.error.ts
  src/utils/exceptions/http-exception.filter.ts
  src/utils/helpers/hash.helper.ts
  src/utils/test-setup/setup.ts
  test/expect/expect-api-error.ts
Labels: 📃 M PR, ✨ feature

#102 Move documentation setup to swagger module
  src/entrypoints/api.ts
  src/utils/swagger/build-api-documentation.ts
  src/utils/swagger/build-web-socket-documentation.ts
  src/utils/swagger/open-api-document.ts
  src/utils/swagger/swagger.ts
Labels: 📃 XS PR, ✨ feature

#103 Refactor/pagination utils
  src/modules/typesense/builder/search-params.builder.ts
  src/modules/typesense/enums/typesense-collection-index.enum.ts
  src/modules/typesense/services/collectors/user-typesense.collector.ts
  src/modules/users/use-cases/view-users/view-users.query.ts
  src/modules/users/use-cases/view-users/view-users.response.ts
  src/utils/pagination/keyset/paginated-keyset.query.ts
  src/utils/pagination/keyset/paginated-keyset.response.ts
  src/utils/pagination/keyset/paginated-result.interface.ts
  src/utils/pagination/keyset/paginated.transformer.ts
  src/utils/pagination/keyset/pagination.decorator.ts
  src/utils/pagination/offset/paginated-offset.query.ts
  src/utils/pagination/offset/paginated-offset.response.ts
  src/utils/pagination/offset/paginated-result.interface.ts
  src/utils/pagination/offset/paginated-transformer.ts
  src/utils/pagination/offset/pagination.decorator.ts
  src/utils/query/pagination/keyset/paginated-search-query.dto.ts
  src/utils/query/pagination/keyset/pagination-query.dto.ts
  src/utils/query/pagination/offset/paginated-search-query.dto.ts
  src/utils/query/pagination/offset/pagination-query.dto.ts
  src/utils/query/query.decorator.ts
  src/utils/query/search.query.ts
  src/utils/query/sort-direction.enum.ts
  src/utils/query/transform-pagination.ts
  src/utils/typeorm/mappers/paginated-offset-query-to-pagination.mapper.ts
  src/utils/typeorm/mappers/sort-direction-to-order.mapper.ts
  src/utils/typeorm/operators/in-or-ignore.ts
Labels: 📃 M PR

#109 Fix ws sending buffer data
  src/modules/websocket/ws-nats.gateway.ts
Labels: 📃 XS PR, 🛠️ bugfix

#108 Composite error
  src/modules/exceptions/api-errors/api-error-response.decorator.ts
  src/modules/exceptions/api-errors/composite.api-error.ts
  src/modules/exceptions/exception.filter.ts
  src/modules/users/use-cases/change-password/change-password.controller.ts
  src/modules/users/use-cases/register-user/register-user.controller.ts
Labels: 📃 XS PR, ✨ feature

#111 implemented async local storage for websocket clients
  src/modules/auth/middleware/auth.middleware.ts
  src/modules/websocket/ws-adapter.ts
  src/modules/websocket/ws-nats.gateway.ts
  src/modules/websocket/ws-topic.validator.ts
  src/modules/websocket/ws.module.ts
Labels: 📃 XS PR, ✨ feature

#112 add app container
  nest-cli.json
  package.json
  pnpm-lock.yaml
  src/entrypoints/api.ts
  src/entrypoints/cronjob.ts
  src/entrypoints/cronjobs/abstract-cronjob/abstract-cronjob.ts
  src/entrypoints/cronjobs/factories/cronjob.factory.ts
  src/entrypoints/cronjobs/import-typesense.cronjob.ts
  src/entrypoints/websocket-server.ts
  src/entrypoints/worker.ts
  src/entrypoints/wss.ts
Labels: 📃 XL PR, ✨ feature

#116 Link aliasName and collectionName before importing to typesense
  src/modules/typesense/services/typesense-initialization.service.ts
Labels: 📃 XS PR, 🛠️ bugfix
