Repository wisemen-digital/nestjs-project-template, pull requests merged in 2024-04, with the labels that each got.

#33 Shared GitHub workflows
  .dockerignore
  .github/dependabot.yaml
  .github/workflows/auto-deploy-to-development.yml
  .github/workflows/deployment.yaml
  .github/workflows/promote-to-enviroment.yml
  .github/workflows/pullrequest-check.yml
  .github/workflows/test.yaml
  .gitignore
  Dockerfile
  docker-compose.yaml
  package.json
Labels: 📃 M PR, ✨ feature

#36 Removed enableImplicitConversion
  src/main.ts
Labels: 📃 XS PR, 🛠️ bugfix

#38 feat: Added status endpoint.
  Dockerfile
  src/app.module.ts
  src/main.ts
  src/modules/status/controllers/status.controller.ts
  src/modules/status/modules/status.module.ts
  src/modules/status/types/api-status.type.ts
Labels: 📃 XS PR, ✨ feature
