Repository wisemen-digital/nestjs-project-template, pull requests merged in 2024-07, with the labels that each got.

#60 add typesense to docker compose
  docker-compose.yaml
Labels: 📃 XS PR, ✨ feature

#63 made user-update dto properties optional
  src/modules/users/dtos/update-user.dto.ts
Labels: 📃 XS PR, ✨ feature

#61 chore: Use provided build arguments
  Dockerfile
  src/modules/status/controllers/status.controller.ts
  src/modules/status/types/api-status.type.ts
Labels: 📃 XS PR, ✨ feature

#65 Bugfix: Arguments are stage specific.
  Dockerfile
Labels: 📃 XS PR, 🛠️ bugfix

#64 Added a bunch of common Date validators to nest project
  src/utils/validators/is-after-date.ts
  src/utils/validators/is-after-today.ts
  src/utils/validators/is-before-today.ts
  src/utils/validators/is-date-without-time-string.validator.ts
  src/utils/validators/is-same-or-after-date.ts
  src/utils/validators/is-same-or-before-date.ts
  src/utils/validators/is-valid-time.ts
  src/utils/validators/tests/is-after-date.test.ts
  src/utils/validators/tests/is-after-today.test.ts
  src/utils/validators/tests/is-before-today.test.ts
  src/utils/validators/tests/is-date-without-time-string.test.ts
  src/utils/validators/tests/is-same-or-after-date.test.ts
  src/utils/validators/tests/is-same-or-before-date.test.ts
  src/utils/validators/tests/is-valid-time.test.ts
Labels: 📃 L PR, ✨ feature

#67 Add queue argument to pgboss worker
  package.json
  pnpm-lock.yaml
  src/entrypoints/pgboss-worker.ts
  src/entrypoints/worker.ts
Labels: 📃 XS PR, ✨ feature

#70 Logic improvements
  src/modules/users/guards/user-update.guard.ts
  src/modules/users/services/user.service.ts
  src/utils/cache/cache.ts
Labels: 📃 XS PR, ✨ feature

#71 Improve generated docs
  src/entrypoints/api.ts
  src/helpers/documentation.ts
  src/modules/auth/controllers/auth.controller.ts
  src/modules/files/controllers/file.controller.ts
  src/modules/files/dtos/create-file.dto.ts
  src/modules/permissions/controllers/permission.controller.ts
  src/modules/roles/controllers/role.controller.ts
  src/modules/status/controllers/status.controller.ts
  src/modules/typesense/controllers/typesense.controller.ts
  src/modules/users/controllers/user.controller.ts
  src/modules/users/dtos/create-user.dto.ts
  src/modules/users/dtos/update-user.dto.ts
  src/modules/users/transformers/user.transformer.ts
Labels: 📃 XS PR, ✨ feature

#72 Cleanup
  src/modules/files/helpers/file-joiner.ts
  src/modules/mail/templates/forgot-password.mjml
  src/modules/users/tests/setup-user.type.ts
Labels: 📃 XS PR, ✨ feature

#66 Remove seeder options
  test/utils/seeder-options.ts
Labels: 📃 XS PR, ✨ feature

#73 Document token call
  package.json
  pnpm-lock.yaml
  src/modules/auth/controllers/auth.controller.ts
  src/modules/auth/types/password-grant.body.ts
  src/modules/auth/types/refresh-grant.body.ts
  src/modules/auth/types/token.response.ts
Labels: 📃 S PR, ✨ feature

#62 replace redis caching by nats caching
  .env.test
  docker-compose.yaml
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/modules/cache/cache.module.ts
  src/modules/cache/cache.service.ts
  src/modules/nats/nats.client.ts
  src/modules/nats/nats.module.ts
  src/modules/permissions/permissions.guard.ts
  src/modules/permissions/transformers/permission.transformer.ts
  src/modules/redis/redis.client.ts
  src/modules/redis/redis.module.ts
  src/modules/roles/dtos/update-roles-bulk.dto.ts
  src/modules/roles/role.module.ts
  src/modules/roles/services/role.service.ts
  src/modules/roles/types/update-role-transformed.type.ts
  src/modules/users/guards/user-update.guard.ts
  src/modules/users/modules/user.module.ts
  src/utils/cache/cache.module.ts
  src/utils/cache/cache.ts
Labels: 📃 L PR, ✨ feature

#76 refactor to the david way
  nest-cli.json
  src/entrypoints/cronjob.ts
  src/entrypoints/cronjobs/abstract-cronjob/abstract-cronjob.ts
  src/entrypoints/cronjobs/factories/cronjob.factory.ts
  src/entrypoints/cronjobs/import-typesense.cronjob.ts
Labels: 📃 S PR, ✨ feature

#68 Feature Nats Publisher
  .github/workflows/pullrequest-check.yml
  nest-cli.json
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/entrypoints/api.ts
  src/entrypoints/websocket-server.ts
  src/modules/nats/nats.client.ts
  src/modules/nats/nats.module.ts
  src/modules/nats/publishers/example.publisher.ts
  src/modules/users/services/user.service.ts
  src/modules/websocket/documentation.md
  src/modules/websocket/dtos/subscribe.dto.ts
  src/modules/websocket/dtos/unsubscribe.dto.ts
  src/modules/websocket/topic.enum.ts
  src/modules/websocket/ws-adapter.ts
  src/modules/websocket/ws-nats.gateway.ts
  src/modules/websocket/ws-topic.validator.ts
  src/modules/websocket/ws.module.ts
Labels: 📃 L PR, ✨ feature
