Repository wisemen-digital/nestjs-project-template, pull requests merged in 2024-05, with the labels that each got.

#40 Refactor: implement onboarding feedback
  src/utils/validators/is-nullable.validator.ts
Labels: 📃 XS PR

#41 Refactored the tests
  src/modules/auth/tests/seeders/client.seeder.ts
  src/modules/auth/tests/seeders/token.seeder.ts
  src/modules/roles/tests/builders/dtos/create-role-dto.builder.ts
  src/modules/roles/tests/builders/entities/role-entity.builder.ts
  src/modules/roles/tests/role-seeder.module.ts
  src/modules/roles/tests/role.e2e.test.ts
  src/modules/roles/tests/role.seeder.ts
  src/modules/roles/tests/seeders/role.seeder.ts
  src/modules/users/controllers/user.controller.ts
  src/modules/users/tests/builders/dtos/create-user-dto.builder.ts
  src/modules/users/tests/builders/entities/user-entity.builder.ts
  src/modules/users/tests/seeders/user.seeder.ts
  src/modules/users/tests/setup-user.type.ts
  src/modules/users/tests/user-seeder.module.ts
  src/modules/users/tests/user.e2e.test.ts
  src/modules/users/tests/user.seeder.ts
  test/seeders/abstract-seeder.ts
  test/setup/setup.ts
  test/utils/test-context.ts
Labels: 📃 L PR, ✨ feature

#43 Removes duplicate file
  src/app.module.ts
  src/utils/typeorm.ts
Labels: 📃 XS PR, 🛠️ bugfix

#42 added files
  .env.test
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/config/sql/migrations/1715334515089-AddFiles.ts
  src/config/sql/migrations/index.ts
  src/config/sql/models/models.ts
  src/modules/files/controllers/file.controller.ts
  src/modules/files/dtos/create-file-entity.dto.ts
  src/modules/files/dtos/create-file.dto.ts
  src/modules/files/entities/file-link.entity.ts
  src/modules/files/entities/file.entity.ts
  src/modules/files/enums/mime-type.enum.ts
  src/modules/files/helpers/file-joiner.ts
  src/modules/files/jobs/remove-unused-file.job.ts
  src/modules/files/modules/file.module.ts
  src/modules/files/repositories/file-link.repository.ts
  src/modules/files/repositories/file.repository.ts
  src/modules/files/services/file-link.service.ts
  src/modules/files/services/file.service.ts
  src/modules/files/services/s3.service.ts
  src/modules/files/tests/builders/create-file-dto.builder.ts
  src/modules/files/tests/builders/file-link.builder.ts
  src/modules/files/tests/file.e2e.test.ts
  src/modules/files/tests/seeders/file.seeder.ts
  src/modules/files/transformers/file-created.transformer.ts
  test/setup/setup.ts
Labels: 📃 XL PR, ✨ feature

#50 Feature: use url instead of port/host
  src/config/env/configuration.ts
  src/config/env/env-configuration.type.ts
  src/utils/cache/cache.module.ts
Labels: 📃 XS PR, ✨ feature
