Repository wisemen-digital/nestjs-project-template, pull requests merged in 2024-08, with the labels that each got.

#58 Update the users role
  src/modules/users/controllers/user.controller.ts
  src/modules/users/dtos/update-user-role.dto.ts
  src/modules/users/modules/user.module.ts
  src/modules/users/services/user-flow.service.ts
  src/modules/users/services/user.service.ts
Labels: 📃 XS PR, ✨ feature

#69 add new test files and add pnpm test:pipeline command
  package.json
  src/app.module.ts
  src/modules/files/tests/file.e2e.test.ts
  src/modules/roles/tests/role.e2e.test.ts
  src/modules/typesense/tests/import-typesense.job.test.ts
  src/modules/users/tests/user.e2e.test.ts
  src/utils/test-setup/global-setup.ts
  src/utils/test-setup/setup.ts
  src/utils/validators/tests/is-after-date.test.ts
  src/utils/validators/tests/is-after-today.test.ts
  src/utils/validators/tests/is-before-today.test.ts
  src/utils/validators/tests/is-date-without-time-string.test.ts
  src/utils/validators/tests/is-same-or-after-date.test.ts
  src/utils/validators/tests/is-same-or-before-date.test.ts
  src/utils/validators/tests/is-valid-time.test.ts
Labels: 📃 S PR, ✨ feature

#83 Feature/Add localizations
  .eslintrc.json
  nest-cli.json
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/config/const.ts
  src/modules/localization/constants/defaults.constant.ts
  src/modules/localization/generated/i18n.generated.ts
  src/modules/localization/modules/localization.module.ts
  src/modules/localization/resources/en/common.json
  src/modules/localization/resources/en/mail.json
  src/modules/localization/services/localization.service.ts
  src/modules/mail/constants/password-reset.constant.ts
  src/modules/mail/content/forgot-password-mail.content.ts
  src/modules/mail/services/mail.service.ts
  src/modules/mail/translations/forgot-password.translation.ts
Labels: 📃 S PR, ✨ feature

#85 Add wip vertical slices for user module
  src/app.module.ts
  src/config/sql/migrations/1723664868518-AddDeletedAtColumnOnUser.ts
  src/config/sql/migrations/index.ts
  src/modules/auth/modules/auth.module.ts
  src/modules/files/modules/file.module.ts
  src/modules/permissions/permissions.decorator.ts
  src/modules/roles/tests/role.e2e.test.ts
  src/modules/typesense/services/collectors/user-typesense.collector.ts
  src/modules/users/controllers/user.controller.ts
  src/modules/users/entities/user.entity.ts
  src/modules/users/modules/user.module.ts
  src/modules/users/queries/user-filter.query.ts
  src/modules/users/queries/user.query.ts
  src/modules/users/repositories/user-typesense.repository.ts
  src/modules/users/services/user-flow.service.ts
  src/modules/users/services/user.service.ts
  src/modules/users/tests/user-entity.builder.ts
  src/modules/users/tests/user.e2e.test.ts
  src/modules/users/tests/user.seeder.ts
  src/modules/users/use-cases/change-password/change-password-command.builder.ts
  src/modules/users/use-cases/change-password/change-password.command.ts
  src/modules/users/use-cases/change-password/change-password.controller.ts
  src/modules/users/use-cases/change-password/change-password.e2e.test.ts
  src/modules/users/use-cases/change-password/change-password.use-case.ts
  src/modules/users/use-cases/change-password/password-changed.response.ts
  src/modules/users/use-cases/change-user-name/change-user-name-command.builder.ts
  src/modules/users/use-cases/change-user-name/change-user-name.command.ts
  src/modules/users/use-cases/change-user-name/change-user-name.controller.ts
  src/modules/users/use-cases/change-user-name/change-user-name.e2e.test.ts
  src/modules/users/use-cases/change-user-name/change-user-name.use-case.ts
  src/modules/users/use-cases/change-user-name/user-name-changed.response.ts
  src/modules/users/use-cases/change-user-role/change-user-role.command.ts
  src/modules/users/use-cases/change-user-role/change-user-role.controller.ts
  src/modules/users/use-cases/change-user-role/change-user-role.use-case.ts
  src/modules/users/use-cases/delete-user/delete-user.controller.ts
  src/modules/users/use-cases/delete-user/delete-user.e2e.test.ts
  src/modules/users/use-cases/delete-user/delete-user.use-case.ts
  src/modules/users/use-cases/register-user/register-user-command.builder.ts
  src/modules/users/use-cases/register-user/register-user.command.ts
  src/modules/users/use-cases/register-user/register-user.controller.ts
  src/modules/users/use-cases/register-user/register-user.e2e.test.ts
  src/modules/users/use-cases/register-user/register-user.use-case.ts
  src/modules/users/use-cases/register-user/user-registered.response.ts
  src/modules/users/use-cases/view-user/view-user.controller.ts
  src/modules/users/use-cases/view-user/view-user.e2e.test.ts
  src/modules/users/use-cases/view-user/view-user.response.ts
  src/modules/users/use-cases/view-user/view-user.use-case.ts
  src/modules/users/use-cases/view-users/view-users.controller.ts
  src/modules/users/use-cases/view-users/view-users.e2e.test.ts
  src/modules/users/use-cases/view-users/view-users.query.ts
  src/modules/users/use-cases/view-users/view-users.response.ts
  src/modules/users/use-cases/view-users/view-users.use-case.ts
  src/modules/users/user.module.ts
  src/modules/websocket/ws.module.ts
  src/utils/pagination/offset/paginated-offset-response.ts
  test/utils/test-context.ts
Labels: 📃 XL PR, ✨ feature

#80 async localstorage auth
  .env.test
  src/app.module.ts
  src/modules/auth/controllers/auth.controller.ts
  src/modules/auth/guards/auth.guard.ts
  src/modules/auth/middleware/auth.middleware.ts
  src/modules/auth/modules/auth.module.ts
  src/modules/auth/services/auth.service.ts
  src/modules/files/controllers/file.controller.ts
  src/modules/permissions/permissions.guard.ts
  src/modules/users/guards/user-update.guard.ts
Labels: 📃 S PR, ✨ feature

#87 Remove helpers directory
  src/entrypoints/api.ts
  src/entrypoints/cronjob.ts
  src/entrypoints/worker.ts
  src/utils/documentation/documentation.ts
  src/utils/sentry/sentry.ts
Labels: 📃 XS PR, ✨ feature

#88 Rename user update guard
  src/modules/cache/cache.service.ts
  src/modules/users/guards/user-is-self-or-admin.guard.ts
  src/modules/users/use-cases/change-password/change-password.controller.ts
  src/modules/users/use-cases/change-user-name/change-user-name.controller.ts
  src/modules/users/use-cases/delete-user/delete-user.controller.ts
  src/modules/users/use-cases/view-user/view-user.controller.ts
Labels: 📃 XS PR, ✨ feature

#89 Replace common param decorator with UuidParam
  src/modules/files/controllers/file.controller.ts
  src/modules/roles/controllers/role.controller.ts
  src/modules/users/use-cases/change-password/change-password.controller.ts
  src/modules/users/use-cases/change-user-name/change-user-name.controller.ts
  src/modules/users/use-cases/change-user-role/change-user-role.controller.ts
  src/modules/users/use-cases/delete-user/delete-user.controller.ts
  src/modules/users/use-cases/view-user/view-user.controller.ts
  src/utils/nest/decorators/uuid-param.ts
Labels: 📃 XS PR, ✨ feature

#90 Refactor test setup
  src/modules/files/tests/file.e2e.test.ts
  src/modules/roles/tests/role.e2e.test.ts
  src/modules/typesense/tests/import-typesense.job.test.ts
  src/modules/users/use-cases/change-password/change-password.e2e.test.ts
  src/modules/users/use-cases/change-user-name/change-user-name.e2e.test.ts
  src/modules/users/use-cases/delete-user/delete-user.e2e.test.ts
  src/modules/users/use-cases/register-user/register-user.e2e.test.ts
  src/modules/users/use-cases/view-user/view-user.e2e.test.ts
  src/modules/users/use-cases/view-users/view-users.e2e.test.ts
  src/utils/test-setup/compile-test-module.ts
  src/utils/test-setup/global-setup.ts
  src/utils/test-setup/setup.ts
  src/utils/validators/tests/is-after-date.test.ts
  src/utils/validators/tests/is-after-today.test.ts
  src/utils/validators/tests/is-before-today.test.ts
  src/utils/validators/tests/is-date-without-time-string.test.ts
  src/utils/validators/tests/is-same-or-after-date.test.ts
  src/utils/validators/tests/is-same-or-before-date.test.ts
  src/utils/validators/tests/is-valid-time.test.ts
Labels: 📃 S PR, ✨ feature

#92 Rename validate password to verify password
  src/modules/users/services/user.service.ts
  src/modules/users/use-cases/change-password/change-password.use-case.ts
  src/utils/helpers/hash.helper.ts
Labels: 📃 XS PR, ✨ feature

#93 Rework global test setup
  src/modules/nats/nats.client.ts
  src/modules/redis/redis.client.ts
  src/utils/test-setup/global-setup.ts
Labels: 📃 XS PR, ✨ feature

#97 Add translation helpers
  src/modules/localization/helpers/translate.helper.ts
  src/modules/localization/modules/localization.module.ts
  src/modules/localization/services/localization.service.ts
  src/modules/mail/services/mail.service.ts
Labels: 📃 S PR, ✨ feature

#94 renamed setupUser to testUser
  src/modules/files/tests/file.e2e.test.ts
  src/modules/roles/tests/role.e2e.test.ts
  src/modules/users/tests/setup-user.type.ts
  src/modules/users/use-cases/change-password/change-password.e2e.test.ts
  src/modules/users/use-cases/change-user-name/change-user-name.e2e.test.ts
  src/modules/users/use-cases/delete-user/delete-user.e2e.test.ts
  src/modules/users/use-cases/view-user/view-user.e2e.test.ts
  src/modules/users/use-cases/view-users/view-users.e2e.test.ts
  test/utils/test-context.ts
Labels: 📃 XS PR, ✨ feature

#99 Rename typesense queries
  src/modules/typesense/controllers/typesense.controller.ts
  src/modules/typesense/dtos/import-typesense.query.ts
  src/modules/typesense/dtos/migrate-typesense.query.ts
  src/modules/typesense/services/typesense-initialization.service.ts
Labels: 📃 XS PR, ✨ feature

#101 Move key utils into auth module
  src/modules/auth/keys/keys.ts
  src/modules/auth/modules/auth.module.ts
  src/modules/auth/tests/seeders/token.seeder.ts
  src/utils/auth/keys.ts
Labels: 📃 XS PR, ✨ feature

#91 Add api errors for user module
  src/modules/users/use-cases/change-password/change-password.controller.ts
  src/modules/users/use-cases/change-password/change-password.e2e.test.ts
  src/modules/users/use-cases/change-password/change-password.use-case.ts
  src/modules/users/use-cases/change-password/invalid-old-password.error.ts
  src/modules/users/use-cases/register-user/email-already-in-use.error.ts
  src/modules/users/use-cases/register-user/register-user.controller.ts
  src/modules/users/use-cases/register-user/register-user.e2e.test.ts
  src/modules/users/use-cases/register-user/register-user.use-case.ts
  src/utils/exceptions/api-errors/api-error-code.decorator.ts
  src/utils/exceptions/api-errors/api-error-meta.decorator.ts
  src/utils/exceptions/api-errors/api-error-response.ts
  src/utils/exceptions/api-errors/api-error-status.decorator.ts
  src/utils/exceptions/api-errors/api-error.ts
  src/utils/exceptions/api-errors/bad-request.api-error.ts
  src/utils/exceptions/api-errors/conflict.api-error.ts
  src/utils/exceptions/http-exception.filter.ts
  src/utils/helpers/hash.helper.ts
  src/utils/test-setup/setup.ts
  test/expect/expect-api-error.ts
Labels: 📃 S PR, ✨ feature
