Repository wisemen-digital/nestjs-project-template, pull requests merged in 2024-01, with the labels that each got.

#8 bugfix authentication
  package.json
  pnpm-lock.yaml
  src/modules/users/services/user.service.ts
Labels: 📃 XS PR, 🛠️ bugfix

#7 Feature/global updates
  .github/workflows/deployment.yaml
  .github/workflows/test.yaml
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/config/sql/migrations/1639661527387-InitialMigration.ts
  src/config/sql/migrations/1643710646293-ClientSeeder.ts
  src/config/sql/migrations/1704190107578-InitialNestMigration.ts
  src/config/sql/migrations/index.ts
  src/config/sql/models/models.ts
  src/config/sql/sources/main.ts
  src/config/sql/utils/typeorm.ts
  src/helpers/sentry.ts
  src/main.ts
  src/modules/auth/controllers/auth.controller.ts
  src/modules/auth/guards/auth.guard.ts
  src/modules/auth/services/auth.service.ts
  src/modules/users/controllers/user.controller.ts
  src/modules/users/dtos/create-user.dto.ts
  src/modules/users/dtos/update-password.dto.ts
  src/modules/users/dtos/update-user.dto.ts
  src/modules/users/services/user.service.ts
  src/modules/users/tests/user.e2e.test.ts
  src/modules/users/transformers/user.transformer.ts
  src/utils/Exceptions/errors.ts
  src/utils/Exceptions/http-exception.filter.ts
Labels: 📃 L PR, ✨ feature

#10 Feature: add dockerfile
  Dockerfile
  package.json
  pnpm-lock.yaml
Labels: 📃 XS PR, ✨ feature

#9 Feature: pagination and query decorators.
  src/utils/pagination/paginated-result.interface.ts
  src/utils/pagination/pagination.decorator.ts
  src/utils/query/paginated-search-query.dto.ts
  src/utils/query/pagination-query.dto.ts
  src/utils/query/query.decorator.ts
  src/utils/query/search-query.dto.ts
  src/utils/query/sort-direction.enum.ts
  src/utils/query/transform-pagination.ts
Labels: 📃 S PR, ✨ feature

#11 Feature: password keys support
  .env.test
  .gitignore
  README.md
  src/modules/auth/modules/auth.module.ts
  src/modules/users/tests/user-seeder.module.ts
  src/utils/auth/keys.ts
Labels: 📃 XS PR, ✨ feature
