Repository wisemen-digital/nestjs-project-template, pull requests merged in 2024-06, with the labels that each got.

#54 Feature/pgboss module
  nest-cli.json
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/entrypoints/api.ts
  src/modules/pgboss/jobs/pgboss.job.ts
  src/modules/roles/role.module.ts
  src/modules/typesense/clients/typesense.client.ts
  src/modules/typesense/modules/typesense.module.ts
  src/modules/users/modules/user.module.ts
  src/utils/Exceptions/errors.interceptor.ts
Labels: 📃 XS PR, ✨ feature

#51 [STRUCTURE REWORK] - file module
  src/app.module.ts
  src/entrypoints/api.ts
  src/modules/auth/guards/auth.guard.ts
  src/modules/auth/services/auth.service.ts
  src/modules/files/controllers/file.controller.ts
  src/modules/files/docs/file-response.docs.ts
  src/modules/files/modules/file.module.ts
  src/modules/files/services/file.flows.service.ts
  src/modules/files/services/file.service.ts
  src/modules/files/services/s3.service.ts
  src/modules/files/tests/file.e2e.test.ts
  src/modules/files/transformers/file-created.transformer.ts
  src/modules/roles/services/role.service.ts
  src/modules/status/controllers/status.controller.ts
  src/modules/users/services/user.service.ts
  src/utils/exceptions/errors.interceptor.ts
  src/utils/exceptions/errors.ts
  src/utils/exceptions/http-exception.filter.ts
  test/expect/expectErrorCode.ts
  test/setup/setup.ts
Labels: 📃 S PR

#56 use the new transaction repository
  src/modules/auth/repositories/client.repository.ts
  src/modules/auth/repositories/pkce.repository.ts
  src/modules/auth/repositories/refresh-token.repository.ts
  src/modules/files/repositories/file-link.repository.ts
  src/modules/files/repositories/file.repository.ts
  src/modules/files/services/file-link.service.ts
  src/modules/roles/repositories/role.repository.ts
  src/modules/roles/services/role.service.ts
  src/modules/typeorm/utils/transaction.ts
  src/modules/typesense/jobs/import-typesense.job.ts
  src/modules/users/repositories/user.repository.ts
Labels: 📃 S PR, ✨ feature

#59 fix searchable field mapping
  src/modules/typesense/collections/abstract-typesense.collection.ts
  src/modules/users/repositories/user-typesense.repository.ts
Labels: 📃 XS PR, 🛠️ bugfix
